/* Oil Palm Basics — figures and sources.
   Photos and figures from the Smallholder Oil Palm Handbook, Modules 1-5,
   3rd edition (2016), Woittiez et al., Wageningen University & SNV,
   licensed CC BY-NC-SA 3.0. Photos by Lotte Woittiez unless a credit is given.
   To add a figure: put the image file beside index.html and add an entry under
   the matching "chapter/topic" key below. */

const FIGURES = {
  "palm/parts": [
    { src: "fig-palm-parts.webp", w: 640, h: 427, full: true,
      cap: { en: "The parts of an oil palm: trunk, crown, youngest and oldest fronds.",
             zh: "油棕的组成部分：树干、树冠、最嫩叶和最老叶。",
             ms: "Bahagian pokok sawit: batang, mahkota, pelepah termuda dan tertua." } },
    { src: "fig-trunk.webp", w: 640, h: 427, full: true,
      cap: { en: "The trunk, its base, and the frond butts left behind after pruning.",
             zh: "树干、基部，以及修叶后留下的叶柄残桩。",
             ms: "Batang, pangkal, dan pangkal pelepah yang tinggal selepas menunas." } },
    { src: "fig-crown.webp", w: 640, h: 427,
      cap: { en: "The crown with developing bunches, and the petiole at the base of each frond.",
             zh: "树冠与发育中的果串，以及每片叶基部的叶柄。",
             ms: "Mahkota dengan tandan sedang membesar, dan petiol di pangkal pelepah." } },
    { src: "fig-leaf.webp", w: 640, h: 480,
      cap: { en: "A frond close up: central rachis with leaflets set at different angles.",
             zh: "叶片特写：中间是叶轴，两侧小叶角度不一。",
             ms: "Pelepah dari dekat: rakis di tengah dengan anak daun pada sudut berbeza." } },
  ],
  "palm/growth": [
    { src: "fig-leaf-numbering.webp", w: 640, h: 528, full: true,
      cap: { en: "Fronds grow in spirals of eight. Leaf 1 sits directly above leaf 9, then 17, then 25.",
             zh: "叶片以 8 片一螺旋生长。叶 1 正上方对应叶 9，再到 17、25。",
             ms: "Pelepah tumbuh dalam lingkaran lapan. Pelepah 1 tepat di atas pelepah 9, kemudian 17, 25." } },
  ],
  "palm/pollination": [
    { src: "fig-male-flower.webp", w: 640, h: 393,
      cap: { en: "A male inflorescence at anthesis — this is where the weevil breeds.",
             zh: "开花期的雄花序——象鼻虫就在这里繁殖。",
             ms: "Infloresen jantan semasa antesis — di sinilah kumbang membiak." } },
    { src: "fig-female-flower.webp", w: 583, h: 736,
      cap: { en: "A female inflorescence. It is only receptive for a short window.",
             zh: "雌花序。可授期很短。",
             ms: "Infloresen betina. Tempoh penerimaannya singkat sahaja." } },
    { src: "fig-hand-pollination.webp", w: 640, h: 454,
      cap: { en: "Hand pollination in a breeding company: the flower is pollinated then bagged.",
             zh: "育种公司的人工授粉：授粉后立即套袋。",
             ms: "Pendebungaan manual di syarikat benih: bunga didebungakan kemudian dibungkus." } },
  ],
  "palm/layout": [
    { src: "fig-layout.webp", w: 640, h: 617, full: true,
      cap: { en: "Block layout: weeded circle, harvesting path, frond stack and inter-row.",
             zh: "地块布局：树盘、收割道、叶堆和行间。",
             ms: "Susun atur blok: bulatan piring, denai tuai, susunan pelepah dan antara barisan." } },
  ],
  "material/three-types": [
    { src: "fig-fruit-parts.webp", w: 640, h: 333, full: true,
      cap: { en: "Tenera (left) and dura (right). Note the fibre ring around the tenera kernel.",
             zh: "Tenera（左）与 dura（右）。注意 tenera 果仁周围的纤维环。",
             ms: "Tenera (kiri) dan dura (kanan). Perhatikan cincin gentian pada tenera." } },
    { src: "fig-shells.webp", w: 640, h: 455, full: true,
      cap: { en: "Shell thickness: dura 2–8 mm, tenera 0.5–2 mm, pisifera none.",
             zh: "果壳厚度：dura 2–8 毫米，tenera 0.5–2 毫米，pisifera 无壳。",
             ms: "Ketebalan tempurung: dura 2–8 mm, tenera 0.5–2 mm, pisifera tiada." } },
    { src: "fig-three-types.webp", w: 640, h: 285,
      cap: { en: "The same three types as real fruit, cut through the middle.",
             zh: "同样三种类型的真实果实，从中间切开。",
             ms: "Tiga jenis yang sama sebagai buah sebenar, dibelah di tengah." } },
  ],
  "material/buying": [
    { src: "fig-certified-seed.webp", w: 640, h: 480,
      cap: { en: "A genuine pre-germinated seed, stamped with the breeding company name.",
             zh: "正规的预发芽种子，印有育种公司名称。",
             ms: "Benih bercambah tulen, bercop nama syarikat benih." } },
  ],
  "material/dura-field": [
    { src: "fig-mixed-fruits.webp", w: 640, h: 307, full: true,
      cap: { en: "Mixed planting material: dura and tenera fruits from the same block.",
             zh: "混杂的种植材料：同一地块里的 dura 和 tenera 果实。",
             ms: "Bahan tanaman bercampur: buah dura dan tenera dari blok yang sama." } },
    { src: "fig-infill.webp", w: 640, h: 427,
      cap: { en: "The palm on the right was planted later to fill an empty point.",
             zh: "右边那株是后来补种的，用来填补空位。",
             ms: "Pokok di kanan ditanam kemudian untuk mengisi tempat kosong." } },
  ],
  "harvest/harvest-how": [
    { src: "fig-harvest-sickle.webp", w: 640, h: 427,
      cap: { en: "Cutting a ripe bunch with a pole sickle.",
             zh: "用长杆镰刀砍下成熟果串。",
             ms: "Memotong tandan masak dengan galah sabit." } },
    { src: "fig-lost-fruit.webp", w: 640, h: 480,
      cap: { en: "Loose fruit left behind has germinated into weeds.",
             zh: "没捡走的散果已经长成了杂草。",
             ms: "Buah lerai yang tertinggal telah tumbuh menjadi rumpai." } },
    { src: "fig-bunch-stacking.webp", w: 640, h: 427,
      cap: { en: "Correct stacking at the roadside — one layer, easy to count and grade.",
             zh: "路边正确的摆放方式——单层，便于清点和分级。",
             ms: "Susunan betul di tepi jalan — satu lapis, mudah dikira dan digred." } },
    { src: "fig-loose-fruit-bag.webp", w: 640, h: 427,
      cap: { en: "Loose fruit collected separately in an empty fertiliser bag.",
             zh: "散果单独装在空肥料袋里。",
             ms: "Buah lerai dikutip berasingan dalam guni baja kosong." } },
  ],
  "harvest/grades": [
    { src: "fig-bunch-good.webp", w: 314, h: 321,
      cap: { en: "Good: full, orange-red, soft, some loose fruit.",
             zh: "合格：饱满、橙红、果软、有少量散果。",
             ms: "Baik: penuh, oren-merah, lembut, ada buah lerai." } },
    { src: "fig-bunch-unripe.webp", w: 253, h: 247,
      cap: { en: "Unripe: mostly black, hard, no loose fruit.",
             zh: "未熟：多为黑色、坚硬、无散果。",
             ms: "Mentah: kebanyakan hitam, keras, tiada buah lerai." } },
    { src: "fig-bunch-underripe.webp", w: 264, h: 247,
      cap: { en: "Underripe: reddish black, still hard.",
             zh: "欠熟：红黑色，仍然坚硬。",
             ms: "Kurang masak: merah kehitaman, masih keras." } },
    { src: "fig-bunch-overripe.webp", w: 346, h: 341,
      cap: { en: "Overripe: many fruits already gone.",
             zh: "过熟：大量果实已经脱落。",
             ms: "Terlebih masak: banyak buah sudah gugur." } },
    { src: "fig-bunch-empty.webp", w: 281, h: 269,
      cap: { en: "Empty: rejected at the mill.",
             zh: "空果串：工厂直接拒收。",
             ms: "Kosong: ditolak di kilang." } },
    { src: "fig-bunch-small.webp", w: 347, h: 291,
      cap: { en: "Small: under 3 kg, usually from very young palms.",
             zh: "小果串：低于 3 公斤，多来自幼龄树。",
             ms: "Kecil: bawah 3 kg, biasanya dari pokok muda." } },
    { src: "fig-bunch-damaged.webp", w: 254, h: 209,
      cap: { en: "Damaged: chewed by rats.",
             zh: "破损：被老鼠啃食。",
             ms: "Rosak: dimakan tikus." } },
    { src: "fig-bunch-longstalk.webp", w: 230, h: 264,
      cap: { en: "Long stalk: weight with no oil, and it soaks oil up in the mill.",
             zh: "长果柄：增重不出油，还会在工厂吸油。",
             ms: "Tangkai panjang: berat tanpa minyak, menyerap minyak di kilang." } },
  ],
  "harvest/transport": [
    { src: "fig-scales.webp", w: 640, h: 427,
      cap: { en: "Hanging scales for weighing bunches. Digital scales are more precise.",
             zh: "用吊秤称果串。有数字秤会更精确。",
             ms: "Penimbang gantung untuk menimbang tandan." } },
    { src: "fig-truck.webp", w: 640, h: 410,
      cap: { en: "Neatly loaded, but the load is too high and should be covered with a net.",
             zh: "装得整齐，但装载过高，而且应该盖网。",
             ms: "Muatan kemas, tetapi terlalu tinggi dan patut ditutup jaring." } },
    { src: "fig-road-bad.webp", w: 640, h: 480,
      cap: { en: "A road in poor condition. Slow transport means higher FFA and a lower price.",
             zh: "路况很差。运输慢＝FFA 升高，价格更低。",
             ms: "Jalan dalam keadaan buruk. Angkutan lambat = ALB naik, harga turun." } },
    { src: "fig-road-good.webp", w: 640, h: 480,
      cap: { en: "The same job done properly — passable all year.",
             zh: "同样的工作做对了——全年可通行。",
             ms: "Kerja yang sama dibuat betul — boleh dilalui sepanjang tahun." } },
  ],
  "maintenance/weeds": [
    { src: "fig-weed-melastoma.webp", w: 607, h: 404,
      cap: { en: "Melastoma malabathricum (senduduk) — also a sign of low phosphorus.",
             zh: "Melastoma malabathricum（senduduk）——也是缺磷的指示植物。",
             ms: "Melastoma malabathricum (senduduk) — juga petanda fosforus rendah." } },
    { src: "fig-weed-clidemia.webp", w: 220, h: 146,
      cap: { en: "Clidemia hirta (soapbush).",
             zh: "Clidemia hirta。",
             ms: "Clidemia hirta." } },
    { src: "fig-weed-chromolaena.webp", w: 367, h: 244,
      cap: { en: "Chromolaena odorata.",
             zh: "Chromolaena odorata。",
             ms: "Chromolaena odorata." } },
    { src: "fig-weed-mimosa.webp", w: 447, h: 298,
      cap: { en: "Mimosa pudica — thorny and unpalatable.",
             zh: "Mimosa pudica（含羞草）——带刺，牲畜不吃。",
             ms: "Mimosa pudica — berduri dan tidak disukai ternakan." } },
    { src: "fig-weed-lantana.webp", w: 606, h: 455,
      cap: { en: "Lantana camara — toxic to livestock.",
             zh: "Lantana camara——对牲畜有毒。",
             ms: "Lantana camara — toksik kepada ternakan." } },
    { src: "fig-weed-dicranopteris.webp", w: 468, h: 350,
      cap: { en: "Dicranopteris linearis — dense fern, blocks access.",
             zh: "Dicranopteris linearis——密生蕨类，妨碍通行。",
             ms: "Dicranopteris linearis — paku padat, menyekat laluan." } },
    { src: "fig-weed-stenochlaena.webp", w: 606, h: 455,
      cap: { en: "Stenochlaena palustris.",
             zh: "Stenochlaena palustris。",
             ms: "Stenochlaena palustris." } },
    { src: "fig-weed-mikania.webp", w: 606, h: 455,
      cap: { en: "Mikania spp. — a climber that smothers young palms.",
             zh: "Mikania spp.——会覆盖幼龄棕的藤蔓。",
             ms: "Mikania spp. — menjalar dan menutup pokok muda." } },
    { src: "fig-weed-asystasia.webp", w: 499, h: 374,
      cap: { en: "Asystasia gangetica.",
             zh: "Asystasia gangetica。",
             ms: "Asystasia gangetica." } },
    { src: "fig-weed-imperata.webp", w: 606, h: 455,
      cap: { en: "Imperata cylindrica (lalang) — not killed by triclopyr.",
             zh: "Imperata cylindrica（lalang）——triclopyr 杀不死。",
             ms: "Imperata cylindrica (lalang) — tidak mati dengan triclopyr." } },
    { src: "fig-poor-weeding.webp", w: 640, h: 480,
      cap: { en: "A poorly weeded block. Noxious weeds have taken over.",
             zh: "除草不到位的地块，恶性杂草已经占领。",
             ms: "Blok yang kurang dirumput. Rumpai merbahaya telah menguasai." } },
    { src: "fig-cover-crop.webp", w: 640, h: 427,
      cap: { en: "A legume cover crop, Calopogonium caeruleum.",
             zh: "豆科覆盖作物 Calopogonium caeruleum。",
             ms: "Tanaman penutup kekacang, Calopogonium caeruleum." } },
    { src: "fig-nephrolepis.webp", w: 640, h: 427,
      cap: { en: "A good soft cover of Nephrolepis ferns.",
             zh: "良好的肾蕨软性地被。",
             ms: "Penutup bumi lembut daripada paku Nephrolepis." } },
  ],
  "maintenance/herbicide": [
    { src: "fig-ppe.webp", w: 640, h: 427,
      cap: { en: "Protective clothing for spraying — note the missing left glove.",
             zh: "喷药用的防护装备——注意左手手套没戴。",
             ms: "Pakaian pelindung untuk menyembur — sarung tangan kiri tiada." } },
    { src: "fig-knapsack.webp", w: 640, h: 387,
      cap: { en: "The parts of a lever-operated knapsack sprayer.",
             zh: "手动背负式喷雾器的构造。",
             ms: "Bahagian penyembur galas tuas." } },
  ],
  "maintenance/circles": [
    { src: "fig-circle-good.webp", w: 640, h: 427,
      cap: { en: "A cleanly weeded circle — loose fruit is easy to spot.",
             zh: "干净的树盘——散果一眼就看得到。",
             ms: "Bulatan piring yang bersih — buah lerai mudah dilihat." } },
    { src: "fig-circle-bad.webp", w: 640, h: 480,
      cap: { en: "A weedy circle with loose fruit hidden underneath.",
             zh: "长满草的树盘，散果全藏在下面。",
             ms: "Bulatan berumpai dengan buah lerai tersembunyi." } },
    { src: "fig-path.webp", w: 640, h: 427,
      cap: { en: "A clear harvesting path — a loaded wheelbarrow can pass easily.",
             zh: "畅通的收割道——装满的推车可以轻松通过。",
             ms: "Denai tuai yang bersih — kereta sorong penuh boleh lalu." } },
  ],
  "maintenance/pruning": [
    { src: "fig-overpruning.webp", w: 640, h: 427,
      cap: { en: "Over-pruning. Fewer fronds means less sunlight captured and less yield.",
             zh: "过度修叶。叶片少＝截光少＝产量低。",
             ms: "Terlalu banyak menunas. Kurang pelepah = kurang cahaya = kurang hasil." } },
    { src: "fig-frond-stack.webp", w: 640, h: 429, full: true,
      cap: { en: "Fronds stacked in the box or U shape between the palms.",
             zh: "叶片在株间排成方框或 U 形。",
             ms: "Pelepah disusun bentuk kotak atau U antara pokok." } },
  ],
  "maintenance/soil": [
    { src: "fig-terrace.webp", w: 640, h: 427,
      cap: { en: "Terracing on sloping ground.",
             zh: "坡地上的梯田。",
             ms: "Teres di tanah bercerun." } },
    { src: "fig-silt-pit.webp", w: 640, h: 427,
      cap: { en: "A silt pit in the inter-row catches runoff and the soil it carries.",
             zh: "行间的淤泥坑，拦截径流和被冲走的土。",
             ms: "Lubang kelodak antara barisan menangkap air larian dan tanah." } },
  ],
  "fertiliser/soils": [
    { src: "fig-peat.webp", w: 640, h: 480,
      cap: { en: "Peat soil: over 60 % organic matter, spongy and dark.",
             zh: "泥炭土：有机质超过 60%，海绵状、颜色深。",
             ms: "Tanah gambut: lebih 60 % bahan organik, berspan dan gelap." } },
    { src: "fig-soil-water.webp", w: 640, h: 419, full: true,
      cap: { en: "How water moves through sand, clay and peat.",
             zh: "水在沙土、黏土和泥炭土中的流动方式。",
             ms: "Bagaimana air bergerak melalui pasir, liat dan gambut." } },
    { src: "fig-peat-water.webp", w: 640, h: 480,
      cap: { en: "Water table control on peat comes before fertiliser.",
             zh: "在泥炭地，控水位比施肥更优先。",
             ms: "Kawalan paras air di gambut didahulukan sebelum baja." } },
  ],
  "fertiliser/deficiency": [
    { src: "fig-leaf-healthy.webp", w: 640, h: 480,
      cap: { en: "A healthy frond: dark green, strong and flexible.",
             zh: "健康的叶片：深绿、结实、有韧性。",
             ms: "Pelepah sihat: hijau tua, kuat dan lentur." } },
    { src: "fig-def-n.webp", w: 640, h: 427,
      cap: { en: "Nitrogen deficiency — pale green to yellow leaflets.",
             zh: "缺氮——小叶呈浅绿至黄色。",
             ms: "Kekurangan nitrogen — anak daun hijau pucat hingga kuning." } },
    { src: "fig-def-p.webp", w: 640, h: 427,
      cap: { en: "Phosphorus deficiency — trunks taper into a pyramid shape.",
             zh: "缺磷——树干呈下粗上细的金字塔形。",
             ms: "Kekurangan fosforus — batang meruncing seperti piramid." } },
    { src: "fig-def-k.webp", w: 640, h: 427,
      cap: { en: "Potassium deficiency — translucent yellow-orange spots on older leaves.",
             zh: "缺钾——老叶上出现透光的黄橙色斑点。",
             ms: "Kekurangan kalium — bintik kuning-oren lutsinar pada pelepah tua." } },
    { src: "fig-white-stripe.webp", w: 640, h: 480,
      cap: { en: "'White stripe' — often too much N with too little K and B.",
             zh: "“白条纹”——常见于氮过量而钾、硼不足。",
             ms: "'White stripe' — selalunya N berlebihan dengan K dan B kurang." } },
    { src: "fig-def-mg.webp", w: 640, h: 427,
      cap: { en: "Magnesium deficiency — only the leaflets in full sun turn yellow.",
             zh: "缺镁——只有受强光照射的小叶变黄。",
             ms: "Kekurangan magnesium — hanya anak daun terdedah matahari menguning." } },
    { src: "fig-def-b-crinkled.webp", w: 640, h: 480,
      cap: { en: "Boron deficiency — crinkled dark green leaves.",
             zh: "缺硼——叶片皱缩、深绿。",
             ms: "Kekurangan boron — daun berkedut hijau tua." } },
    { src: "fig-def-b-hooked.webp", w: 640, h: 480,
      cap: { en: "Boron deficiency — hooked leaflet tips.",
             zh: "缺硼——小叶尖端呈钩状。",
             ms: "Kekurangan boron — hujung anak daun berkait." } },
    { src: "fig-def-cuzn.webp", w: 640, h: 480,
      cap: { en: "'Peat yellows' — copper or zinc deficiency, seen on peat only.",
             zh: "“泥炭黄化”——缺铜或缺锌，只在泥炭地出现。",
             ms: "'Peat yellows' — kekurangan kuprum atau zink, di gambut sahaja." } },
  ],
  "fertiliser/placement": [
    { src: "fig-poor-spreading.webp", w: 640, h: 453,
      cap: { en: "Fertiliser dumped in a heap instead of spread. Most of it is wasted.",
             zh: "肥料堆成一堆而不是撒开，大部分都浪费了。",
             ms: "Baja ditimbun bukan ditabur. Kebanyakannya terbazir." } },
    { src: "fig-efb-good.webp", w: 640, h: 427,
      cap: { en: "Correct EFB application — a patch one bunch thick between the palms.",
             zh: "正确的空果串施用——在株间铺一层厚的一块。",
             ms: "Penggunaan EFB betul — petak setebal satu tandan antara pokok." } },
    { src: "fig-efb-bad.webp", w: 640, h: 480,
      cap: { en: "Wrong: EFB piled around the circle, hiding loose fruit.",
             zh: "错误：空果串堆在树盘周围，挡住散果。",
             ms: "Salah: EFB ditimbun sekeliling bulatan, menutup buah lerai." } },
  ],
  "pests/rats": [
    { src: "fig-rat.webp", w: 627, h: 943, credit: "IRRI photos, Wikimedia Commons",
      cap: { en: "Rattus spp. They breed fast, so a small population becomes a big one.",
             zh: "Rattus spp.。繁殖极快，小种群很快变大。",
             ms: "Rattus spp. Ia membiak cepat." } },
    { src: "fig-rat-damage.webp", w: 640, h: 480,
      cap: { en: "A bunch chewed by rats — oil lost, and a deduction at the mill.",
             zh: "被老鼠啃过的果串——损失油，工厂还要扣重。",
             ms: "Tandan dimakan tikus — minyak hilang dan dipotong di kilang." } },
    { src: "fig-barn-owl.webp", w: 640, h: 481,
      cap: { en: "Barn owl (Tyto alba). One nest box every 5–10 hectares.",
             zh: "仓鸮（Tyto alba）。每 5–10 公顷设一个巢箱。",
             ms: "Burung hantu (Tyto alba). Satu kotak sarang setiap 5–10 hektar." } },
  ],
  "pests/oryctes": [
    { src: "fig-oryctes.webp", w: 640, h: 463,
      cap: { en: "Rhinoceros beetle, Oryctes rhinoceros.",
             zh: "犀牛甲虫 Oryctes rhinoceros。",
             ms: "Kumbang badak, Oryctes rhinoceros." } },
    { src: "fig-oryctes-base.webp", w: 640, h: 426,
      cap: { en: "Damage at the base of an immature palm.",
             zh: "幼龄棕基部的危害。",
             ms: "Kerosakan di pangkal pokok belum matang." } },
    { src: "fig-oryctes-leaf.webp", w: 640, h: 426,
      cap: { en: "Mature palm damage — chunks missing, triangular leaf tips.",
             zh: "成龄棕的危害——叶片缺口，叶尖呈三角形。",
             ms: "Kerosakan pokok matang — berketul hilang, hujung bersegi tiga." } },
    { src: "fig-oryctes-larva.webp", w: 640, h: 417,
      cap: { en: "A larva found under an empty fruit bunch pile. Kill it and spread the pile thinner.",
             zh: "在空果串堆下找到的幼虫。杀掉，并把果串摊薄。",
             ms: "Larva di bawah timbunan tandan kosong. Bunuh dan nipiskan timbunan." } },
  ],
  "pests/leafeaters": [
    { src: "fig-nettle-caterpillar.webp", w: 640, h: 480, credit: "L.P. Koh, Flickr",
      cap: { en: "A nettle caterpillar.",
             zh: "刺蛾幼虫。",
             ms: "Ulat api." } },
    { src: "fig-leaf-damage.webp", w: 640, h: 480,
      cap: { en: "Severe leaf-eating damage — only the midribs are left.",
             zh: "严重的食叶危害——只剩下中脉。",
             ms: "Kerosakan teruk — hanya tulang tengah tinggal." } },
    { src: "fig-turnera.webp", w: 640, h: 480,
      cap: { en: "Turnera subulata (bunga pukul lapan) feeds the natural enemies of caterpillars.",
             zh: "Turnera subulata（八点钟花）能养活毛虫的天敌。",
             ms: "Turnera subulata (bunga pukul lapan) memberi makan musuh semula jadi ulat." } },
  ],
  "pests/ganoderma": [
    { src: "fig-ganoderma.webp", w: 594, h: 1056,
      cap: { en: "A Ganoderma-infected palm: spear leaves bunched, dead fronds hanging like a skirt.",
             zh: "感染灵芝菌的植株：矛叶堆积，枯叶像裙子一样垂挂。",
             ms: "Pokok dijangkiti Ganoderma: pelepah tombak berkumpul, pelepah mati tergantung." } },
    { src: "fig-ganoderma-bracket.webp", w: 484, h: 363, full: true,
      cap: { en: "A bracket on the trunk. Cut it off, take it out of the field and burn it.",
             zh: "树干上的菌盖。割掉、带出园区、烧毁。",
             ms: "Cendawan pada batang. Potong, keluarkan dari ladang dan bakar." } },
  ],
  "pests/rots": [
    { src: "fig-spear-rot.webp", w: 640, h: 853,
      cap: { en: "Spear rot — the spear leaf has turned brown and collapsed.",
             zh: "矛叶腐烂——矛叶变褐并倒塌。",
             ms: "Reput tombak — pelepah tombak bertukar perang dan rebah." } },
    { src: "fig-spear-rot-detail.webp", w: 640, h: 853,
      cap: { en: "Spear rot, close up.",
             zh: "矛叶腐烂特写。",
             ms: "Reput tombak, dari dekat." } },
  ],
  "mill/process": [
    { src: "fig-mill-bunches.webp", w: 640, h: 480, full: true,
      cap: { en: "Delivered bunches waiting to be processed at the mill.",
             zh: "送到工厂、等待加工的果串。",
             ms: "Tandan yang dihantar menunggu diproses di kilang." } },
  ],
};

/* ---------------- sources actually used in this app ---------------- */

const SOURCES = [
  {
    group: { en: "Main textbook — the Smallholder Oil Palm Handbook",
             zh: "主要教材 —— Smallholder Oil Palm Handbook",
             ms: "Buku teks utama — Smallholder Oil Palm Handbook" },
    note: { en: "Woittiez, L.S., Haryono, S., Turhina, S., Dani, H., Dukan, T.P. & Smit, H. (2016). 3rd edition. Wageningen University, Wageningen, and SNV International Development Organisation, The Hague. Licensed CC BY-NC-SA 3.0. All five modules were used, and every photograph in this app comes from them.",
            zh: "Woittiez, L.S., Haryono, S., Turhina, S., Dani, H., Dukan, T.P. 与 Smit, H.（2016），第 3 版。Wageningen 大学与 SNV 国际发展组织。授权方式 CC BY-NC-SA 3.0。五个模块全部使用，本 App 里的所有照片都出自这套教材。",
            ms: "Woittiez, L.S., Haryono, S., Turhina, S., Dani, H., Dukan, T.P. & Smit, H. (2016). Edisi ke-3. Wageningen University dan SNV. Dilesenkan CC BY-NC-SA 3.0. Kelima-lima modul digunakan, dan semua foto dalam aplikasi ini datang daripadanya." },
    items: [
      { title: "Module 1: Planting Material (24 pp.)",
        used: { en: "Chapter 02 in full — dura, pisifera and tenera, the shell gene, seed buying and the 20-seed check, dura census and the five options.",
                zh: "完整对应第 02 章 —— dura、pisifera、tenera，果壳基因，购种与 20 粒检验，dura 普查与五种处理方案。",
                ms: "Bab 02 sepenuhnya — dura, pisifera dan tenera, gen tempurung, membeli benih dan semakan 20 benih." } },
      { title: "Module 2: Harvesting, Grading, Transport (25 pp.)",
        used: { en: "Chapter 03 — income drivers, the harvesting standard and method, the eight bunch categories, grading vs sorting, weighing, transport and roads.",
                zh: "第 03 章 —— 收入构成、收割标准与步骤、八类果串、grading 与 sorting 的区别、过磅、运输与道路。",
                ms: "Bab 03 — pemacu pendapatan, piawaian menuai, lapan kategori tandan, grading lawan sorting, timbang, angkut dan jalan." } },
      { title: "Module 3: Plantation Maintenance (53 pp.)",
        used: { en: "Chapter 01 palm anatomy and block layout, and Chapter 04 in full — noxious weeds, herbicides and spraying safety, circles and paths, pruning standards, frond stacking, soil conservation.",
                zh: "第 01 章的植株结构与地块布局，以及完整的第 04 章 —— 恶性杂草、除草剂与喷药安全、树盘与收割道、修叶标准、叶堆摆放、水土保持。",
                ms: "Bab 01 anatomi pokok dan susun atur blok, dan Bab 04 sepenuhnya — rumpai merbahaya, racun rumpai, bulatan dan denai, piawaian menunas, susunan pelepah." } },
      { title: "Module 4: Fertiliser Application (64 pp.)",
        used: { en: "Chapter 05 in full — the 4R principle, nutrient removal, soil types, fertiliser nutrient contents, the mature and immature rate tables, deficiency symptoms, placement and timing, empty fruit bunches, leaf sampling.",
                zh: "完整对应第 05 章 —— 4R 原则、养分带走量、土壤类型、肥料养分含量、成龄与未成龄施肥量表、缺素症状、施肥位置与时机、空果串、叶片取样。",
                ms: "Bab 05 sepenuhnya — prinsip 4R, nutrien dibawa keluar, jenis tanah, kandungan nutrien baja, jadual kadar, simptom kekurangan, penempatan dan masa." } },
      { title: "Module 5: Pests and Diseases (29 pp.)",
        used: { en: "Chapter 06 in full — the census, rats and barn owls, rhinoceros beetle, leaf-eating caterpillars and beneficial plants, Ganoderma, spear rot, crown disease and bud rot.",
                zh: "完整对应第 06 章 —— 普查、老鼠与仓鸮、犀牛甲虫、食叶毛虫与有益植物、灵芝菌基腐病、矛叶腐烂、冠腐病与芽腐病。",
                ms: "Bab 06 sepenuhnya — banci, tikus dan burung hantu, kumbang badak, ulat pemakan daun, Ganoderma, reput tombak, penyakit mahkota dan reput pucuk." } }
    ]
  },
  {
    group: { en: "Malaysian statistics and regulation",
             zh: "马来西亚统计与法规",
             ms: "Statistik dan peraturan Malaysia" },
    items: [
      { title: "MPOB, Overview of the Malaysian Oil Palm Industry 2025",
        url: "https://bepi.mpob.gov.my/images/overview/Overview2025.pdf",
        used: { en: "Every Malaysian figure in Key numbers and in Chapter 08: planted area 5.70 M ha, CPO production 20.28 Mt, estate FFB yield 17.77 t/ha, national OER 19.74 %, CPO RM 4,292.50/t, mill-gate FFB RM 930/t, FFB at 1 % OER RM 47.39.",
                zh: "「关键数字」和第 08 章里所有马来西亚数据：种植面积 570 万公顷、毛棕榈油产量 2,028 万吨、种植园 FFB 产量 17.77 吨／公顷、全国出油率 19.74%、CPO 每吨 RM4,292.50、厂门 FFB 每吨 RM930、每 1% 出油率 RM47.39。",
                ms: "Semua angka Malaysia dalam Angka utama dan Bab 08: kawasan tanaman 5.70 juta ha, pengeluaran CPO 20.28 juta tan, hasil BTS ladang 17.77 t/ha, KPM 19.74 %." } },
      { title: "Malaysian Palm Oil Board Act 1998 (Act 582) and MPOB Licensing Regulations 2005; MPOB, Criteria and Guidelines on MPOB License Application",
        url: "https://e-lesen.mpob.gov.my",
        used: { en: "Chapter 08 — which activities need a licence, the 40.46 ha smallholder threshold, free smallholder licences, dealer (DF) licence conditions.",
                zh: "第 08 章 —— 哪些活动需要准证、40.46 公顷的小农界线、小农准证免费、果商（DF）准证的条件。",
                ms: "Bab 08 — aktiviti yang perlukan lesen, had 40.46 ha pekebun kecil, lesen pekebun kecil percuma, syarat lesen peniaga (DF)." } },
      { title: "MSPO scheme documents, Malaysian Standard MS 2530:2022 series",
        url: "https://mspo.org.my/standards/",
        used: { en: "Chapter 08 — MSPO being compulsory rather than voluntary, the Part 2-1 to 4-3 split, greenhouse gas and labour requirements, and the link between MSPO certification and MPOB licence renewal.",
                zh: "第 08 章 —— MSPO 属强制而非自愿、Part 2-1 至 4-3 的分册、温室气体与劳工要求，以及 MSPO 认证与 MPOB 准证续期的挂钩。",
                ms: "Bab 08 — MSPO wajib bukan sukarela, pembahagian Bahagian 2-1 hingga 4-3, keperluan gas rumah hijau dan buruh." } }
    ]
  },
  {
    group: { en: "Research and technical references",
             zh: "研究与技术资料",
             ms: "Rujukan penyelidikan dan teknikal" },
    items: [
      { title: "Research on Elaeidobius kamerunicus in Malaysia (Syed et al., 1982 onward; FELDA Sahabat fruit-set study, Sabah)",
        used: { en: "Chapter 01 pollination — the 1981 introduction from Cameroon, the end of routine hand pollination, and the finding that over about 5,000 weevils per hectare held fruit set and fruit-to-bunch above 60 %.",
                zh: "第 01 章授粉部分 —— 1981 年从喀麦隆引入、人工授粉从此基本停止，以及每公顷约 5,000 只以上象鼻虫可把结实率和果占串比维持在 60% 以上的研究结果。",
                ms: "Bab 01 pendebungaan — pengenalan 1981 dari Cameroon, berakhirnya pendebungaan manual, dan dapatan ~5,000 kumbang sehektar mengekalkan set buah melebihi 60 %." } },
      { title: "AOCS technical overview of palm oil; published studies on palm oil mill by-products and POME",
        url: "https://www.aocs.org/resource/palm-oil/",
        used: { en: "Chapter 07 — mill throughput of 60–100 t FFB/h, the process line from sterilisation to kernel drying, oil loss points, POME at about 0.65 t per tonne of FFB, and by-product yields of 230–250 kg EFB, 130–150 kg fibre, 60–65 kg shell and 55–60 kg kernel per tonne.",
                zh: "第 07 章 —— 工厂处理量 60–100 吨／小时、从蒸煮到烘干果仁的流程、油损失点、POME 约每吨鲜果串 0.65 吨，以及每吨副产品 230–250 公斤空果串、130–150 公斤纤维、60–65 公斤果壳、55–60 公斤果仁。",
                ms: "Bab 07 — kapasiti kilang 60–100 t/jam, aliran proses, titik kehilangan minyak, POME ~0.65 t setiap tan BTS, dan hasil sampingan setiap tan." } },
      { title: "MPOB research on oil palm planting density (Oil Palm Industry Economic Journal)",
        used: { en: "Key numbers — the conventional 136–148 palms per hectare on inland mineral soil, and higher densities on deep peat.",
                zh: "「关键数字」—— 内陆矿质土常规密度每公顷 136–148 株，以及深泥炭土采用更高密度。",
                ms: "Angka utama — kepadatan lazim 136–148 pokok sehektar di tanah mineral, dan lebih tinggi di gambut dalam." } }
    ]
  }
];

/* Photo credits where the handbook names someone other than Lotte Woittiez:
   fig-rat — IRRI photos, Wikimedia Commons
   fig-nettle-caterpillar — L.P. Koh, Flickr */
